<?php

namespace app\components;

final class Yii3PackageHelper
{
    public const PACKAGES_BY_GROUPS = [
        'Container & Proxy' => [
            'di',
            'factory',
            'definitions',
            'container-proxy',
            'proxy',
            'injector',
        ],
        'Core & Common' => [
            'config',
            'aliases',
            'arrays',
            'files',
            'json',
            'network-utilities',
            'requirements',
            'strings',
            'var-dumper',
            'classifier',
        ],
        'Databases' => [
            'db',
            'db-mssql',
            'db-mysql',
            'db-oracle',
            'db-pgsql',
            'db-sqlite',
            'db-migration',
            'active-record',
            'yii-cycle',
        ],
        'Data abstractions' => [
            'data',
            'data-db',
            'data-cycle',
            'yii-dataview',
        ],
        'Cache' => [
            'cache',
            'cache-apcu',
            'cache-db',
            'cache-file',
            'cache-memcached',
            'cache-redis',
            'cache-wincache',
        ],
        'Security' => [
            'security',
            'csrf',
            'proxy-middleware',
            'access',
            'auth',
            'auth-jwt',
            'rbac',
            'rbac-cycle-db',
            'rbac-db',
            'rbac-php',
            'rbac-rules-container',
            'user',
            'yii-auth-client',
        ],
        'HTTP & Web' => [
            'http',
            'yii-http',
            'middleware-dispatcher',
            'http-middleware',
            'yii-middleware',
            'cookies',
            'session',
            'input-http',
            'request-body-parser',
            'request-provider',
            'response-download',
            'router',
            'router-fastroute',
            'file-router',
            'rate-limiter',
            'psr-emitter',
        ],
        'Forms & Validation' => [
            'form',
            'form-model',
            'validator',
            'hydrator',
            'hydrator-validator',
            'request-model',
        ],
        'View & Templating' => [
            'html',
            'view',
            'view-twig',
            'yii-view-renderer',
            'widget',
            'yii-widgets',
            'assets',
            'bootstrap5',
            'yii-bulma',
            'yii-twig',
        ],
        'Internationalization' => [
            'i18n',
            'translator',
            'translator-extractor',
            'translator-formatter-intl',
            'translator-message-db',
            'translator-message-gettext',
            'translator-message-php',
        ],
        'Queue & Tasks' => [
            'queue',
            'queue-amqp',
            'queue-db',
            'queue-redis',
        ],
        'Logging' => [
            'log',
            'log-target-db',
            'log-target-email',
            'log-target-file',
            'log-target-syslog',
        ],
        'Mailer' => [
            'mailer',
            'mailer-swiftmailer',
            'mailer-symfony',
            'mailer-view',
        ],
        'Console' => [
            'yii-console',
        ],
        'Events' => [
            'event-dispatcher',
            'yii-event',
        ],
        'Dev Tools & Debug' => [
            'error-handler',
            'friendly-exception',
            'yii-debug',
            'yii-debug-api',
            'yii-debug-viewer',
            'yii-dev-tool',
            'yii-gii',
            'profiler',
            'yii-sentry',
            'code-style',
        ],
        'APIs' => [
            'yii-swagger',
            'data-response',
        ],
        'Testing' => [
            'test-support',
            'yii-testing',
        ],
        'Runners' => [
            'yii-runner',
            'yii-runner-console',
            'yii-runner-frankenphp',
            'yii-runner-http',
            'yii-runner-roadrunner',
        ],
        'Mutex' => [
            'mutex',
            'mutex-file',
            'mutex-pdo-mysql',
            'mutex-pdo-oracle',
            'mutex-pdo-pgsql',
            'mutex-redis',
        ],
    ];
}
