#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');
defined('VENDOR_DIR') or define ('VENDOR_DIR', __DIR__ . '/../vendor');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$vendorDir = rtrim(getenv('VENDOR_DIR'), '/');

require($vendorDir . '/autoload.php');
require($vendorDir . '/yiisoft/yii2/Yii.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/config/console.php'),
    require(__DIR__ . '/config/console-local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
