<?php
return [
    [
        'name' => 'Qiang Xue',
        'id' => '2',
        'forumName' => 'qiang',
        'memberSince' => 'Jan 2008',
        'location' => 'Washington DC, USA',
        'duty' => 'Founder and project lead',
        'photo' => 'https://avatars2.githubusercontent.com/u/993322?v=3&s=460',
        'github' => 'qiangxue',
        'twitter' => 'qiang_xue',
        'active' => true,
    ],
    [
        'name' => 'Alexander Makarov',
        'id' => '415',
        'forumName' => 'samdark',
        'memberSince' => 'Mar 2010',
        'location' => 'Russia',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars0.githubusercontent.com/u/47294?v=3&s=460',
        'github' => 'samdark',
        'twitter' => 'sam_dark',
        'active' => true,
    ],
    [
        'name' => 'Maurizio Domba Cerin',
        'id' => '2650',
        'forumName' => 'mdomba',
        'memberSince' => 'Aug 2010',
        'location' => 'Rovinj, Croatia',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars1.githubusercontent.com/u/209837?v=3&s=460',
        'github' => 'mdomba',
        'twitter' => 'mdomba',
        'active' => false,
    ],
    [
        'name' => 'Carsten Brandt',
        'id' => '5951',
        'forumName' => 'CeBe',
        'memberSince' => 'Aug 2012',
        'location' => 'Berlin, Germany',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars0.githubusercontent.com/u/189796?v=3&s=460',
        'github' => 'cebe',
        'twitter' => 'cebe_cc',
        'active' => true,
    ],
    [
        'name' => 'Klimov Paul',
        'id' => '117134',
        'forumName' => 'Klimov Paul',
        'memberSince' => 'Mar 2013',
        'location' => ' Donetsk, Ukraine',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars1.githubusercontent.com/u/1482054?v=3&s=460',
        'github' => 'klimov-paul',
        'twitter' => 'klimov_paul',
        'active' => true,
    ],
    [
        'name' => 'Antonio Ramirez',
        'id' => '7106',
        'forumName' => 'Antonio Ramirez',
        'memberSince' => 'May 2013',
        'location' => 'Majorca, Balearic Islands, Spain',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars2.githubusercontent.com/u/566016?v=3&s=460',
        'github' => 'tonydspaniard',
        'twitter' => 'tonydspaniard',
        'active' => false,
    ],
    [
        'name' => 'Timur Ruziev',
        'id' => '9061',
        'forumName' => 'resurtm',
        'memberSince' => 'Mar 2013',
        'location' => 'Almaty, Kazakhstan',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars0.githubusercontent.com/u/100198?v=3&s=460',
        'github' => 'resurtm',
        'active' => false,
    ],
    [
        'name' => 'Wei Zhuo',
        'id' => '3',
        'forumName' => 'wei',
        'memberSince' => 'Jan 2008 - Dec 2014',
        'location' => 'Sydney, Australia',
        'duty' => 'Project site maintenance and development',
        'photo' => 'https://avatars0.githubusercontent.com/u/448167?v=3&s=460',
        'github' => 'xwz',
        'active' => false,
    ],
    [
        'name' => 'Sebastián Thierer',
        'id' => '54',
        'forumName' => 'sebas',
        'memberSince' => 'Sep 2009 - Dec 2014',
        'location' => 'Argentina',
        'duty' => 'Component development',
        'photo' => 'https://avatars1.githubusercontent.com/u/1434034?v=3&s=460',
        'github' => 'sebathi',
        'active' => false,
    ],
    [
        'name' => 'Jeffrey Winesett',
        'id' => '15',
        'forumName' => 'jefftulsa',
        'memberSince' => 'Sep 2010 - Dec 2014',
        'location' => 'Austin, TX, USA',
        'duty' => 'Documentation and marketing',
        'photo' => 'https://avatars2.githubusercontent.com/u/299167?v=3&s=460',
        'github' => 'jefftulsa',
        'active' => false,
    ],
    [
        'name' => 'Y!!',
        'id' => '1644',
        'forumName' => 'Y!!',
        'memberSince' => 'Aug 2010 - May 2012',
        'location' => 'Germany',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars0.githubusercontent.com/u/100198?v=3&s=460',
        'active' => false,
    ],
    [
        'name' => 'Jonah Turnquist',
        'id' => '127',
        'forumName' => 'jonah',
        'memberSince' => 'Sep 2009 - Aug 2010',
        'location' => 'California, US',
        'duty' => 'Component development',
        'photo' => 'https://avatars0.githubusercontent.com/u/100198?v=3&s=460',
        'active' => false,
    ],
    [
        'name' => 'István Beregszászi',
        'id' => '1286',
        'forumName' => 'pestaa',
        'memberSince' => 'Sep 2009 - Mar 2010',
        'location' => 'Hungary',
        'duty' => 'Core framework development',
        'photo' => 'https://avatars2.githubusercontent.com/u/187342?v=3&s=460',
        'github' => 'pestaa',
        'active' => false,
    ],
];
