<?php
return [
    [
        'name' => 'Qiang Xue',
        'id' => '2',
        'forumName' => 'qiang',
        'memberSince' => 'Jan 2008',
        'location' => 'Washington DC, USA',
        'duty' => 'Founder and project lead',
        'photo' => '/image/team/qiangxue.jpg',
        'github' => 'qiangxue',
        'twitter' => 'qiang_xue',
        'active' => true,
    ],
    [
        'name' => 'Alexander Makarov',
        'id' => '415',
        'forumName' => 'samdark',
        'memberSince' => 'Mar 2010',
        'location' => 'Russia',
        'duty' => 'Core framework development',
        'photo' => '/image/team/samdark.jpg',
        'github' => 'samdark',
        'twitter' => 'sam_dark',
        'active' => true,
    ],
    [
        'name' => 'Maurizio Domba Cerin',
        'id' => '2650',
        'forumName' => 'mdomba',
        'memberSince' => 'Aug 2010 - Nov 2013',
        'location' => 'Rovinj, Croatia',
        'duty' => 'Core framework development',
        'photo' => '/image/team/mdomba.jpg',
        'github' => 'mdomba',
        'twitter' => 'mdomba',
        'active' => false,
    ],
    [
        'name' => 'Carsten Brandt',
        'id' => '5951',
        'forumName' => 'CeBe',
        'memberSince' => 'Aug 2012',
        'location' => 'Berlin, Germany',
        'duty' => 'Core framework development',
        'photo' => '/image/team/cebe.png',
        'github' => 'cebe',
        'twitter' => 'cebe_cc',
        'active' => true,
    ],
    [
        'name' => 'Klimov Paul',
        'id' => '117134',
        'forumName' => 'Klimov Paul',
        'memberSince' => 'Mar 2013',
        'location' => ' Donetsk, Ukraine',
        'duty' => 'Core framework development',
        'photo' => '/image/team/klimov-paul.jpg',
        'github' => 'klimov-paul',
        'twitter' => 'klimov_paul',
        'active' => true,
    ],
    [
        'name' => 'Antonio Ramirez',
        'id' => '7106',
        'forumName' => 'Antonio Ramirez',
        'memberSince' => 'May 2013 - Jun 2014',
        'location' => 'Majorca, Balearic Islands, Spain',
        'duty' => 'Core framework development',
        'photo' => '/image/team/tonydspaniard.jpg',
        'github' => 'tonydspaniard',
        'twitter' => 'tonydspaniard',
        'active' => false,
    ],
    [
        'name' => 'Timur Ruziev',
        'id' => '9061',
        'forumName' => 'resurtm',
        'memberSince' => 'Mar 2013',
        'location' => 'Almaty, Kazakhstan',
        'duty' => 'Core framework development',
        'photo' => '/image/team/noimage.png',
        'github' => 'resurtm',
        'active' => false,
    ],
    [
        'name' => 'Wei Zhuo',
        'id' => '3',
        'forumName' => 'wei',
        'memberSince' => 'Jan 2008 - Dec 2014',
        'location' => 'Sydney, Australia',
        'duty' => 'Project site maintenance and development',
        'photo' => '/image/team/xwz.jpg',
        'github' => 'xwz',
        'active' => false,
    ],
    [
        'name' => 'Sebastián Thierer',
        'id' => '54',
        'forumName' => 'sebas',
        'memberSince' => 'Sep 2009 - Dec 2014',
        'location' => 'Argentina',
        'duty' => 'Component development',
        'photo' => '/image/team/sebathi.png',
        'github' => 'sebathi',
        'active' => false,
    ],
    [
        'name' => 'Jeffrey Winesett',
        'id' => '15',
        'forumName' => 'jefftulsa',
        'memberSince' => 'Sep 2010 - Dec 2014',
        'location' => 'Austin, TX, USA',
        'duty' => 'Documentation and marketing',
        'photo' => '/image/team/jefftulsa.jpg',
        'github' => 'jefftulsa',
        'active' => false,
    ],
    [
        'name' => 'Y!!',
        'id' => '1644',
        'forumName' => 'Y!!',
        'memberSince' => 'Aug 2010 - May 2012',
        'location' => 'Germany',
        'duty' => 'Core framework development',
        'photo' => '/image/team/noimage.png',
        'active' => false,
    ],
    [
        'name' => 'Jonah Turnquist',
        'id' => '127',
        'forumName' => 'jonah',
        'memberSince' => 'Sep 2009 - Aug 2010',
        'location' => 'California, US',
        'duty' => 'Component development',
        'photo' => '/image/team/noimage.png',
        'active' => false,
    ],
    [
        'name' => 'István Beregszászi',
        'id' => '1286',
        'forumName' => 'pestaa',
        'memberSince' => 'Sep 2009 - Mar 2010',
        'location' => 'Hungary',
        'duty' => 'Core framework development',
        'photo' => '/image/team/pestaa.jpg',
        'github' => 'pestaa',
        'active' => false,
    ],
];
